config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  scope module: 'admins' do
    get 'admin_home'
    get 'notifications'
    resources :puzzles
    resources :memories
    resources :tournaments
    resources :contributors, only: [:new, :create, :destroy, :edit, :update, :index]
    resources :text_memories
    resources :image_memories
    resources :puzzle_contenders, only: [:new, :create, :destroy] do
      resources :votes
    end
  end
  scope module: 'visitors' do
    root to: "home#index"
    post 'votes', to: 'home#votes'
    get '/home/current_puzzle' => 'home#current_puzzle', as: 'current_puzzle'
    get '/home/puzzle/:id' => 'puzzles#show', as: 'visitors_puzzle' 
    get '/home/puzzles/index' => 'puzzles#index', as: 'visitors_puzzles'
    get '/home/tournaments'  => 'home#tournaments', as: 'visitor_torunaments'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contributor.rb
class Contributor < ApplicationRecord
  belongs_to :puzzle
end

app/models/image_memory.rb
class ImageMemory < ApplicationRecord
  belongs_to :memory
  has_one_attached :image
end

app/models/memory.rb
class Memory < ApplicationRecord
  has_many :image_memories, dependent: :destroy
  has_many :text_memories, dependent: :destroy
  belongs_to :puzzle
  accepts_nested_attributes_for :image_memories, :text_memories
  validates :user_names42, presence: true

  def active_memories
    image_memories.where(active: true).count + text_memories.where(active: true).count > 0 ? true : nil
  end
end

app/models/puzzle.rb
class Puzzle < ApplicationRecord
	has_many :memories, dependent: :destroy
	has_many :contributors, dependent: :destroy
	has_many :puzzle_contenders, dependent: :destroy
	has_one_attached :image
end

app/models/puzzle_contender.rb
class PuzzleContender < ApplicationRecord
  belongs_to :tournament
  belongs_to :puzzle
  has_many :votes, dependent: :destroy
  validate :duplicated_puzzle

  private

    def duplicated_puzzle
      if self.tournament.puzzles.where(id: puzzle_id).any?
        errors.add(:puzzle_id, "The puzzle already belongs to this Tournament")
      end
    end
end

app/models/text_memory.rb
class TextMemory < ApplicationRecord
  belongs_to :memory
  validates :title, :description, presence: true
end

app/models/tournament.rb
class Tournament < ApplicationRecord
	has_many :puzzle_contenders, dependent: :destroy
	has_many :puzzles, through: :puzzle_contenders
	has_many :votes, through: :puzzle_contenders
	
	def available_puzzle_contenders
		Puzzle.where.not(id: self.puzzles)
	end
	
	def current_winner
      self.puzzle_contenders.map { |contender| [contender.votes.count, contender]}.group_by { |element| element [0] }.max(3)
    end

    def active
    	start_date < Time.now && end_date > Time.now
    end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :puzzle_contender
  validates_presence_of :username
  validate :valid_user_42api, :duplicated_vote, :active_tournament

  private

    def valid_user_42api
      user = username.downcase.strip
      client = OAuth2::Client.new(Rails.application.credentials.api42_uid, Rails.application.credentials.api42_secret, site: "https://api.intra.42.fr")
      token = client.client_credentials.get_token
      puts ">>>" * 10 + "---" * 20 + "<<<" * 10
      begin
        response = token.get("/v2/users/" + user)
        puts "Response: (should be 200): " + response.status.to_s
        puts "New Vote registered"
        puts "Login: " + response.parsed["login"]
        puts "Campus: " + response.parsed["campus"].first["country"]
        puts "Puzzle: " + self.puzzle_contender.puzzle.title +  " | Last Votes Count: " + self.puzzle_contender.votes.count.to_s
      rescue
        puts "something went wrong when check if #{user} exists..."
        errors.add(:username, "Not a valid username __REASON_TODO__")
      end
      puts ">>>" * 10 + "-*-" * 20 + "<<<" * 10
    end

    def duplicated_vote
      if self.puzzle_contender.tournament.votes.where(username: username).any?
          errors.add(:username, "That username has been used once already :( ")
      end
    end

    def active_tournament
      if not self.puzzle_contender.tournament.active
        errors.add(:puzzle_contender, "The Tournament is not active atm :( ")
      end
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contributors_helper.rb
module ContributorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/memories_helper.rb
module MemoriesHelper
end

app/helpers/puzzle_helper.rb
module PuzzleHelper
end

app/helpers/puzzles_helper.rb
module PuzzlesHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/admins/_side_bar.html.erb
<div class="container side-bar-container">
	<div class="fixed-bar">
		<h3 class="text-center home-btn p-4">
			<%= link_to admin_home_path, class: "text-decoration-none text-dark" do%>
				<span class="material-icons">home</span> Admin
			<% end %>
		</h3>
		<%= link_to puzzles_path, class: "btn btn-light btn-lg p-2 side-link mb-3 d-block d-flex justify-content-around" do %>
			Puzzles <span class="material-icons" style="color: palevioletred;">extension</span>
		<% end %>
		<%= link_to notifications_path, class: "btn btn-light btn-lg p-2 side-link mb-3 d-block d-flex justify-content-around" do %>
			<% unless @notifications_count != 0 %>
				Notifications <span class="material-icons text-secondary">notifications_active</span>
			<% else %>
				Notifications <span class="material-icons text-danger shake">notifications_active</span>
			<% end %>
		<% end %>
		<%= link_to tournaments_path, class: "btn btn-light btn-lg p-2 side-link mb-3 d-block d-flex justify-content-around" do %>
			Tournaments<span class="material-icons" style="color: goldenrod;">emoji_events</span>
		<% end %>
		<%= link_to contributors_path, class: "btn btn-light btn-lg p-2 side-link mb-3 d-block d-flex justify-content-around" do %>
			Contributors<span class="material-icons">inventory_2</span>
		<% end %>
	</div>
</div>

app/views/admins/admin_home.html.erb
<div class="jumbotron bg-light p-2 admin-jumbotron">
  <h1 class="display-4">Hello, <%= current_admin.email.split('@').first %>!</h1>
  <p class="lead">You have [<%= link_to @total_notifications.to_s, notifications_path %>] notifications.</p>
  <hr class="my-4">
  <p class="lead">Total Puzzles: <%= @puzzles.count %></p>
  <p class="lead">Active Torunaments: <%= @tournaments.select { |tournament| tournament.active }.count %></p>
  <p class="lead">Total Torunaments: <%= @tournaments.count %></p>
  <p class="lead">Total Votes: <%= @tournaments.map { |x| x.votes.count }.sum %></p>
  <p class="lead">Total Contributors: <%= @contributors.count %></p>
  <p class="lead">
    <%= link_to "Website", root_path, class: "btn btn-primary btn-lg" %>
  </p>
</div>

app/views/admins/notifications.html.erb
<div class="jumbotron bg-light jumbotron-fluid admin-jumbotron">
  <div class="container p-0">
    <h1 class="display-4 text-center">Notifications</h1>
    <ul>
    	<li><p class="lead">Image Memories to review <span class="badge badge-pill bg-secondary"><%= @image_memories.count %></span></p></li>
    	<li><p class="lead">Text Memories to review <span class="badge badge-pill bg-secondary"><%= @text_memories.count %></span></p></li>
    </ul>
    <div class="row m-0 p-2 d-flex justify-content-center">
	    <% @image_memories.each do |memory| %>
			<div class="card col-sm-6 col-md-4 col-lg-3 p-0 m-1 border-secondary">
			  <span class="badge badge-pill bg-warning notification-image-badge">image</span>
			  <span class="p-0 m-0 notification-image-container">
				<% if memory.image.present? %>
					<%= image_tag memory.image, class: 'rounded img-fluid' %>
				<% else %>
					<p class="card-text">No image available...</p>
				<% end %>
				<p class="text-center bg-none notification-image-puzzle-button">
					<%= link_to memory.memory.puzzle, class: 'btn btn-outline-primary bg-light' do %>
						<%= memory.memory.puzzle.title %>
					<% end %>
			  	</p>
			  </span>
			  <div class="card-body pt-1">
			    <p class="card-text m-0">Alt: <%= memory.alt %></p>
			    <p class="card-text border border-secondary rounded d-inline-block p-1 m-0"><%= memory.memory.user_names42 %></p>
			  	<hr>
			    <div class="d-flex m-auto justify-content-between">
			    	<div>
			    		<%= form_with(model: memory) do |form| %>
							<%= form.hidden_field :active, value: true %>
							<%= button_tag(type: "submit", class: 'btn btn-success btn-sm m-3') do %>
      							<span class="material-icons">task_alt</span>
    						<% end %>
			    		<% end %>
			  		</div>
			  		<div class="mt-auto mb-auto">
			    		<%= link_to 'Destroy', memory, method: :delete, class: 'btn btn-danger btn-sm' %>
			  		</div>

			  	</div>
			  </div>
			</div>
		<% end %>
		<% @text_memories.each do |memory| %>
			<div class="card p-1 col-sm-6 col-md-4 col-lg-3 m-1 border-secondary">
			  <p class="text-end m-0 p-0"><span class="badge badge-pill bg-info">text</span></p>
			  <div class="card-body">
			    <h4 class="card-title">Title: <%= memory.title %></h4>
			    <p class="card-text p-0 m-0">Descr.: <%= memory.description %></p>
			    <p class="card-text border border-secondary rounded d-inline-block p-1"><%= memory.memory.user_names42 %></p>
			    <p class="text-center p-0 m-0">
				    <%= link_to memory.memory.puzzle, class: 'btn btn-outline-primary' do %>
				  		<%= memory.memory.puzzle.title %>
				  	<% end %>
			  	</p>
			    <hr>
			    <div class="d-flex m-auto justify-content-between">
			    	<div>
			    		<%= form_with(model: memory) do |form| %>
							<%= form.hidden_field :active, value: true %>
							<%= button_tag(type: "submit", class: 'btn btn-success btn-sm m-3') do %>
      							<span class="material-icons">task_alt</span>
    						<% end %>
			    		<% end %>
			    	</div>
			    	<div class="mt-auto mb-auto">
			    		<%= link_to 'Destroy', memory, method: :delete, class: 'btn btn-danger btn-sm' %>
			    	</div>
			  	</div>
			  </div>
			</div>
		<% end %>
	</div>
  </div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Puzzle42</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Material+Icons">
    <%= stylesheet_link_tag 'admins', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='row admin-content'>
      <div class="col-md-2 side_bar">
        <%= render 'side_bar' %>
      </div>
      <div class="col-md-10 p-0">
        <p class="notice"><%= notice %></p>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Puzzle42</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/visitor.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Puzzle42</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Material+Icons">
    <%= stylesheet_link_tag 'visitors', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'visitors', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <span class="logo-home">
      <%= link_to root_path, class: "disable-link" do %>
        <span class="material-icons">extension</span>
        <p>42</p>
      <% end %>
    </span>
    <%= yield %>
  </body>
</html>