config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  scope module: 'admins' do
    get 'admin_home'
    get 'notifications'
    resources :puzzles
    resources :memories
    resources :tournaments
    resources :contributors, only: [:new, :create, :destroy, :edit, :update, :index]
    resources :text_memories
    resources :image_memories
    resources :puzzle_contenders, only: [:new, :create, :destroy] do
      resources :votes
    end
  end
  scope module: 'visitors' do
    root to: "home#index"
    post 'votes', to: 'home#votes'
    get '/home/current_puzzle' => 'home#current_puzzle', as: 'current_puzzle'
    get '/home/puzzle/:id' => 'puzzles#show', as: 'visitors_puzzle' 
    get '/home/puzzles/index' => 'puzzles#index', as: 'visitors_puzzles'
    get '/home/tournaments'  => 'home#tournaments', as: 'visitor_torunaments'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contributor.rb
class Contributor < ApplicationRecord
  belongs_to :puzzle
end

app/models/image_memory.rb
class ImageMemory < ApplicationRecord
  belongs_to :memory
  has_one_attached :image
end

app/models/memory.rb
class Memory < ApplicationRecord
  has_many :image_memories, dependent: :destroy
  has_many :text_memories, dependent: :destroy
  belongs_to :puzzle
  accepts_nested_attributes_for :image_memories, :text_memories
  validates :user_names42, presence: true

  def active_memories
    image_memories.where(active: true).count + text_memories.where(active: true).count > 0 ? true : nil
  end
end

app/models/puzzle.rb
class Puzzle < ApplicationRecord
	has_many :memories, dependent: :destroy
	has_many :contributors, dependent: :destroy
	has_many :puzzle_contenders, dependent: :destroy
	has_one_attached :image
end

app/models/puzzle_contender.rb
class PuzzleContender < ApplicationRecord
  belongs_to :tournament
  belongs_to :puzzle
  has_many :votes, dependent: :destroy
  validate :duplicated_puzzle

  private

    def duplicated_puzzle
      if self.tournament.puzzles.where(id: puzzle_id).any?
        errors.add(:puzzle_id, "The puzzle already belongs to this Tournament")
      end
    end
end

app/models/text_memory.rb
class TextMemory < ApplicationRecord
  belongs_to :memory
  validates :title, :description, presence: true
end

app/models/tournament.rb
class Tournament < ApplicationRecord
	has_many :puzzle_contenders, dependent: :destroy
	has_many :puzzles, through: :puzzle_contenders
	has_many :votes, through: :puzzle_contenders
	
	def available_puzzle_contenders
		Puzzle.where.not(id: self.puzzles)
	end
	
	def current_winner
      self.puzzle_contenders.map { |contender| [contender.votes.count, contender]}.group_by { |element| element [0] }.max(3)
    end

    def active
    	start_date < Time.now && end_date > Time.now
    end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :puzzle_contender
  validates_presence_of :username
  validate :valid_user_42api, :duplicated_vote, :active_tournament

  private

    def valid_user_42api
      user = username.downcase.strip
      client = OAuth2::Client.new(Rails.application.credentials.api42_uid, Rails.application.credentials.api42_secret, site: "https://api.intra.42.fr")
      token = client.client_credentials.get_token
      puts ">>>" * 10 + "---" * 20 + "<<<" * 10
      begin
        response = token.get("/v2/users/" + user)
        puts "Response: (should be 200): " + response.status.to_s
        puts "New Vote registered"
        puts "Login: " + response.parsed["login"]
        puts "Campus: " + response.parsed["campus"].first["country"]
        puts "Puzzle: " + self.puzzle_contender.puzzle.title +  " | Last Votes Count: " + self.puzzle_contender.votes.count.to_s
      rescue
        puts "something went wrong when check if #{user} exists..."
        errors.add(:username, "Not a valid username __REASON_TODO__")
      end
      puts ">>>" * 10 + "-*-" * 20 + "<<<" * 10
    end

    def duplicated_vote
      if self.puzzle_contender.tournament.votes.where(username: username).any?
          errors.add(:username, "That username has been used once already :( ")
      end
    end

    def active_tournament
      if not self.puzzle_contender.tournament.active
        errors.add(:puzzle_contender, "The Tournament is not active atm :( ")
      end
    end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :authenticate_admin!, :notifications_count
	layout 'admin'

	def admin_home
		@puzzles = Puzzle.all
		@total_notifications = ImageMemory.where(active: false).count + TextMemory.where(active: false).count
		@tournaments = Tournament.all
		@contributors = Contributor.all
	end

	def notifications
		@image_memories = ImageMemory.where(active: false)
		@text_memories = TextMemory.where(active: false)
	end

	private

		def notifications_count
			@notifications_count = ImageMemory.where(active: false).count + TextMemory.where(active: false).count
		end
end

app/controllers/visitors/home_controller.rb
module Visitors
  class HomeController < VisitorsController
    before_action :set_puzzle_contender, only: %i[ votes ]
    def index
      @tournaments = Tournament.all
      @puzzle_shelve = Puzzle.all.order(:created_at).select { |x| x.image.present? }.max(5)
      @contributors = Contributor.where(is_finished: false)
    end

    def tournaments
      @tournaments = Tournament.all.select { |tournament| tournament.active }
    end

    def votes
      unless @contender.nil?        
        @vote = @contender.votes.build(vote_params)
        if @vote.save
          notice = "Vote was successfully submited!"
        else
          notice = "Invalid username..."
        end
      else
        notice = "Sorry you cannot vote for that contender... :("
      end
      redirect_to visitor_torunaments_path, notice: notice
    end

    def current_puzzle
      @contributors = Contributor.where(is_finished: false)
    end
    private

      def set_puzzle_contender
        @contender = PuzzleContender.find(params[:vote][:puzzle_contender_id])
      end

      def vote_params
        params.require(:vote).permit(:username, :puzzle_contender_id)
      end
  end
end

app/controllers/visitors/puzzles_controller.rb
module Visitors
  class PuzzlesController < VisitorsController

    def show
      @puzzle = Puzzle.find(params[:id])
    end

    def index
    end
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
	layout 'visitor'
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contributors_helper.rb
module ContributorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/memories_helper.rb
module MemoriesHelper
end

app/helpers/puzzle_helper.rb
module PuzzleHelper
end

app/helpers/puzzles_helper.rb
module PuzzlesHelper
end

app/helpers/text_memories_helper.rb
module TextMemoriesHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/visitors/home/_vote_form.html.erb
<%= form_with(model: vote) do |form| %>
	<p class="input">
		<label>[user@42]$
        	<%= form.text_field :username %>
		</label>
	</p>
	<%= form.hidden_field :puzzle_contender_id, value: vote.puzzle_contender.id %>	
  	<div class="actions submit-vote">
    	<%= form.submit "Vote" %>
  	</div>
<% end %>

app/views/visitors/home/current_puzzle.html.erb
<% if @contributors.any? %>
	<% @contributors.each do |contributor| %>
		<div class="container">
			<h1 class="title">
				<%= contributor.puzzle.title %>
				<hr>
			</h1>
			<div class="body-image">
				<div class="image">
					<% if contributor.puzzle.image.present? %>
						<%= image_tag contributor.puzzle.image %>
					<% end %>
				</div>
			</div>
			<h5 class="body-text">
				<%= contributor.puzzle.description %>
				<br>
				<p class="badge badge-purple"><%= contributor.puzzle.pieces %> pc</p>
				<p class="badge badge-gray"><%= ((Time.now - contributor.created_at) / 1.hour).round %> hrs</p>
			</h5>
		</div>
	<% end %>
<% else %>
	<div class="container">
		<span class="no-contributors">
			<p>No current puzzles...</p>
			<%= link_to "Go Back", root_path, class: "disable-link" %>
		</span>
	</div>
<% end %>

app/views/visitors/home/index.html.erb
<div class="puzzle-piece-container">
	<div class="puzzle-piece-element" id="puzzle-piece-1">
		<%= link_to current_puzzle_path, class: "disable-link" do %>
			<div class="piece-section">
				<h1>PUZZLE</h1>
				<div class="contributor">
					<% if @contributors.any? %>
						<% if @contributors.first.puzzle.image.present? %>
							<%= image_tag  @contributors.first.puzzle.image %>
						<% else %>
							<p>Open <%= @contributors.first.puzzle.title %></p>
						<% end %>
					<% else %>
						<p>No puzzles ATM... :(</p>
					<% end %>
				</div>
			</div>
		<% end %>
	</div>
	
	<div class="puzzle-piece-element" id="puzzle-piece-2">
		<%= link_to visitor_torunaments_path, class: "disable-link" do %>
			<div class="piece-section ">
				<h1>TOURNAMENTS</h1>
				<ul class="tournament-list">
					<li><%= @tournaments.select { |tournament| tournament.active }.count %> tournaments</li>
					<% if @tournaments.select { |tournament| tournament.active }.any? %>
						<li><%= @tournaments.select { |tournament| tournament.active }.map { |active_tournament| active_tournament.puzzle_contenders.count }.sum %> contenders</li>
						<li><%= @tournaments.select { |tournament| tournament.active }.map { |active_tournament| active_tournament.votes.count }.sum %> votes</li>
					<% else %>
						<li>No contenders :(</li>
						<li>No votes :(</li>
					<% end %>
				</ul>
				<div class="home-page-icon">
					<span class="material-icons">emoji_events</span>
				</div>
			</div>
		<% end %>
	</div>
	
	<div class="puzzle-piece-element" id="puzzle-piece-3">
		<div class="puzzle-shelve-container piece-section ">
			<h1><%= link_to "PUZZLE SHELVE", visitors_puzzles_path, class: "disable-link" %></h1>
			<span class="shelve-container">
				<% @puzzle_shelve.each do |puzzle| %>
					<%= link_to visitors_puzzle_path(puzzle), class: "shelve-item" do %>
						<% if puzzle.image.present? %>
							<%= image_tag puzzle.image %>
						<% else %>
							<p><%= puzzle.title %></p>
						<% end %>
					<% end %>
				<% end %>
			</span>
			<div class="home-page-icon">
				<span class="material-icons">reorder</span>
			</div>
		</div>
	</div>
	
	<div class="puzzle-piece-element" id="puzzle-piece-4">
		<div class="piece-section ">
			<h1>PUZZLECLUB<span class="text-purple">42</span></h1>
			<div>
				<p class="club-info-title" >Lisbon42 Puzzle club official website.</p>
				<h5 class="club-info-description">
					This club is for anyone who enjoys puzzles.
					<br>
					<br>
					This Club host two activities:
					<ul>
						<li>Jigasaw Puzzles</li>
						<li>Lego Building</li>
					</ul>
					<div class="club-info-buttons">
						<%= link_to "Tournament", visitor_torunaments_path %>
						<%= link_to "CurrentPuzzle", current_puzzle_path %>
					</div>
				</h5>
			</div>
			<div class="home-page-icon">
				<span class="icon-42">42</span>
			</div>
		</div>
	</div>
</div>

app/views/visitors/home/tournaments.html.erb
<div class="tournament-container">
	<div class="tournaments-box">
		<h1>Tournaments</h1>
		<h6>Welcome to the tournaments. Vote for the next puzzle!</h6>
		<hr>
		<ul>
			<li><span class="num-stat"><%= @tournaments.count %></span> Active</li>
			<li><span class="num-stat"><%= @tournaments.map { |t| t.votes.count }.sum %> </span><%= "Vote".pluralize(@tournaments.map { |t| t.votes.count }.sum) %></li>
			<li><span class="num-stat"><%= @tournaments.map { |t| t.puzzle_contenders.count }.sum %></span> <%= "Contender".pluralize(2) %></li>
		</ul>
		<div class="tournaments-sliders">
			<div class="slides-container">
				<% @tournaments.each_with_index do |tournament, index| %>
					<% if @tournaments.first.eql?(tournament) %>
						<div class="slider-slide active" id="slide-<%= index %>" data-id="<%= index %>">
					<% else %>
						<div class="slider-slide" id="slide-<%= index %>" data-id="<%= index %>">
					<% end %>
						<h4><%= tournament.title %><br><span style="font-size: 50%;">Choose a puzzle</span><br><button style="font-size: 50%;">&nbspEnds at <%= tournament.end_date.strftime("%d/%m/%Y") %>&nbsp</button></h4>
						<ul>
							<% tournament.puzzle_contenders.each do |contender| %>
								<li class="puzzle-contender-image" data-contenderid="<%= contender.id%>">
									<% if contender.puzzle.image.present? %>
										<%= image_tag contender.puzzle.image%>
										<span class="votes">
											<%= contender.votes.count %>
										</span>
									<% else %>
										<h6 class="contender-no-img"><%= contender.puzzle.title%>
											<span class="votes-no-img">
												<%= contender.votes.count %>
											</span>
										</h6>
									<% end %>
								</li>
								<div class="vote-container" id="vote-<%= contender.id %>">
									<div class="vote-form">
										<h1>Vote for <%= contender.puzzle.title %>
											<br>
											<span>Enter your intra username</span>
										</h1>
										<%= render "vote_form", vote: contender.votes.build %>
										<ul class="wizard">
											<li><span>h</span>help</li>
											<li class="escape-puzzle"><span>ESC</span>exit!</li>
										</ul>
									</div>
								</div>
							<% end %>
						</ul>
					</div>
				<% end %>
				<% if @tournaments.any? %>
					<div id="pagination">
						<div data-tournamentid="before_button" class="disable-link">&laquo;</div>
						<% @tournaments.each_with_index do |tournament, index| %>
							<div data-tournamentid="<%= index %>" class="disable-link"><%= index %></div>
						<% end %>
						<div data-tournamentid="after_button" class="disable-link">&raquo;</div>
					</div>
				<% else %>
					<br>
					<br>
					<br>
					<hr>
					<h1>0 tournaments available :(</h1>
					<hr>
				<% end %>
			</div>
		</div>
		<% @tournaments %>
	</div>
</div>