config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  scope module: 'admins' do
    get 'admin_home'
    get 'notifications'
    resources :puzzles
    resources :memories
    resources :tournaments
    resources :contributors, only: [:new, :create, :destroy, :edit, :update, :index]
    resources :text_memories
    resources :image_memories
    resources :puzzle_contenders, only: [:new, :create, :destroy] do
      resources :votes
    end
  end
  scope module: 'visitors' do
    root to: "home#index"
    post 'votes', to: 'home#votes'
    get '/home/current_puzzle' => 'home#current_puzzle', as: 'current_puzzle'
    get '/home/puzzle/:id' => 'puzzles#show', as: 'visitors_puzzle' 
    get '/home/puzzles/index' => 'puzzles#index', as: 'visitors_puzzles'
    get '/home/tournaments'  => 'home#tournaments', as: 'visitor_torunaments'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contributor.rb
class Contributor < ApplicationRecord
  belongs_to :puzzle
end

app/models/image_memory.rb
class ImageMemory < ApplicationRecord
  belongs_to :memory
  has_one_attached :image
end

app/models/memory.rb
class Memory < ApplicationRecord
  has_many :image_memories, dependent: :destroy
  has_many :text_memories, dependent: :destroy
  belongs_to :puzzle
  accepts_nested_attributes_for :image_memories, :text_memories
  validates :user_names42, presence: true

  def active_memories
    image_memories.where(active: true).count + text_memories.where(active: true).count > 0 ? true : nil
  end
end

app/models/puzzle.rb
class Puzzle < ApplicationRecord
	has_many :memories, dependent: :destroy
	has_many :contributors, dependent: :destroy
	has_many :puzzle_contenders, dependent: :destroy
	has_one_attached :image
end

app/models/puzzle_contender.rb
class PuzzleContender < ApplicationRecord
  belongs_to :tournament
  belongs_to :puzzle
  has_many :votes, dependent: :destroy
  validate :duplicated_puzzle

  private

    def duplicated_puzzle
      if self.tournament.puzzles.where(id: puzzle_id).any?
        errors.add(:puzzle_id, "The puzzle already belongs to this Tournament")
      end
    end
end

app/models/text_memory.rb
class TextMemory < ApplicationRecord
  belongs_to :memory
  validates :title, :description, presence: true
end

app/models/tournament.rb
class Tournament < ApplicationRecord
	has_many :puzzle_contenders, dependent: :destroy
	has_many :puzzles, through: :puzzle_contenders
	has_many :votes, through: :puzzle_contenders
	
	def available_puzzle_contenders
		Puzzle.where.not(id: self.puzzles)
	end
	
	def current_winner
      self.puzzle_contenders.map { |contender| [contender.votes.count, contender]}.group_by { |element| element [0] }.max(3)
    end

    def active
    	start_date < Time.now && end_date > Time.now
    end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :puzzle_contender
  validates_presence_of :username
  validate :valid_user_42api, :duplicated_vote, :active_tournament

  private

    def valid_user_42api
      user = username.downcase.strip
      client = OAuth2::Client.new(Rails.application.credentials.api42_uid, Rails.application.credentials.api42_secret, site: "https://api.intra.42.fr")
      token = client.client_credentials.get_token
      puts ">>>" * 10 + "---" * 20 + "<<<" * 10
      begin
        response = token.get("/v2/users/" + user)
        puts "Response: (should be 200): " + response.status.to_s
        puts "New Vote registered"
        puts "Login: " + response.parsed["login"]
        puts "Campus: " + response.parsed["campus"].first["country"]
        puts "Puzzle: " + self.puzzle_contender.puzzle.title +  " | Last Votes Count: " + self.puzzle_contender.votes.count.to_s
      rescue
        puts "something went wrong when check if #{user} exists..."
        errors.add(:username, "Not a valid username __REASON_TODO__")
      end
      puts ">>>" * 10 + "-*-" * 20 + "<<<" * 10
    end

    def duplicated_vote
      if self.puzzle_contender.tournament.votes.where(username: username).any?
          errors.add(:username, "That username has been used once already :( ")
      end
    end

    def active_tournament
      if not self.puzzle_contender.tournament.active
        errors.add(:puzzle_contender, "The Tournament is not active atm :( ")
      end
    end
end

app/controllers/admins/tournaments_controller.rb
module Admins
  class TournamentsController < AdminsController
    before_action :set_tournament, only: %i[ show edit update destroy ]

    def index
      @tournaments = Tournament.all
    end

    def show
      @total_votes = @tournament.puzzle_contenders.map { |contender| contender.votes.count }.sum
      @contender = PuzzleContender.new
      @vote = Vote.new
    end

    def new
      @tournament = Tournament.new
    end

    def edit
    end

    def create
      @tournament = Tournament.new(tournament_params)

      respond_to do |format|
        if @tournament.save
          format.html { redirect_to @tournament, notice: "Tournament was successfully created." }
          format.json { render :show, status: :created, location: @tournament }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @tournament.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        if @tournament.update(tournament_params)
          format.html { redirect_to @tournament, notice: "Tournament was successfully updated." }
          format.json { render :show, status: :ok, location: @tournament }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @tournament.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @tournament.destroy
      respond_to do |format|
        format.html { redirect_to tournaments_url, notice: "Tournament was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private

      def set_tournament
        @tournament = Tournament.find(params[:id])
      end

      def tournament_params
        params.require(:tournament).permit(:start_date, :end_date, :title)
      end
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :authenticate_admin!, :notifications_count
	layout 'admin'

	def admin_home
		@puzzles = Puzzle.all
		@total_notifications = ImageMemory.where(active: false).count + TextMemory.where(active: false).count
		@tournaments = Tournament.all
		@contributors = Contributor.all
	end

	def notifications
		@image_memories = ImageMemory.where(active: false)
		@text_memories = TextMemory.where(active: false)
	end

	private

		def notifications_count
			@notifications_count = ImageMemory.where(active: false).count + TextMemory.where(active: false).count
		end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contributors_helper.rb
module ContributorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/memories_helper.rb
module MemoriesHelper
end

app/helpers/puzzle_helper.rb
module PuzzleHelper
end

app/helpers/puzzles_helper.rb
module PuzzlesHelper
end

app/helpers/text_memories_helper.rb
module TextMemoriesHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/admins/tournaments/_contenders_form.html.erb
<% if tournament.available_puzzle_contenders.any? %>
	<%= form_with(model: contender) do |form| %>
		<% if contender.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(contender.errors.count, "error") %> prohibited this contender from being saved:</h2>

		      <ul>
		        <% contender.errors.each do |error| %>
		          <li><%= error.full_message %></li>
		        <% end %>
		      </ul>
		    </div>
	  <% end %>

	  <%= form.hidden_field :tournament_id, value: tournament.id %>
		  <div class="field">
		  	<%= form.label :puzzle_id, class: "form-control"%>
		  	<%= form.collection_select :puzzle_id, tournament.available_puzzle_contenders, :id, :title, {}, class: "form-control" %>
		  </div>
		  <div class="actions">
		  	<%= form.submit class: "btn btn-primary btn-block mt-2" %>
		  </div>
	<% end %>
<% else %>
	<p>There are no available contenders at the moment.</p>
<% end %>

app/views/admins/tournaments/_form.html.erb
<%= form_with(model: tournament) do |form| %>
  <% if tournament.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tournament.errors.count, "error") %> prohibited this tournament from being saved:</h2>

      <ul>
        <% tournament.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group form-field date-field">
    <div class="field-tag">
      <div class="input-group-prepend" >
        <span class="input-group-text tag-style">
          <%= form.label :start_date %>
        </span>
      </div>
    </div>
    <%= form.datetime_select :start_date, class: "form-control" %>
  </div>

  <div class="input-group form-field date-field">
    <div class="field-tag">
      <div class="input-group-prepend" >
        <span class="input-group-text tag-style">
          <%= form.label :end_date %>
        </span>
      </div>
    </div>
    <%= form.datetime_select :end_date, class: "date-form" %>
  </div>

  <div class="input-group form-field">
    <div class="field-tag">
      <div class="input-group-prepend" >
        <span class="input-group-text tag-style">
          <%= form.label :title %>
        </span>
      </div>
    </div>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="actions text-center">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/admins/tournaments/_vote_contender_form.html.erb
<%= form_with(model: [contender, vote]) do |form| %>
	<%= form.hidden_field :vote, value: vote %>
	<%= form.hidden_field :username, value: "arosado-  " %>
	<div class="actions text-center">
    	<%= form.submit "vote", class: "btn btn-primary btn-sm" do %>
		<% end %>
  	</div>
<% end %>

app/views/admins/tournaments/edit.html.erb
<div class="card m-0 p-0 no-border-card">
    <div class="d-flex justify-content-around">
      <%= link_to 'Back', tournaments_path, class: 'btn btn-dark m-3 col-2' %>
      <%= link_to @tournament, class: 'btn btn-dark m-3 col-2' do %>
        <span class="material-icons">visibility</span>
      <% end %>
    </div>
  <div class="card-body text-center">
    <h2 class="card-title">Editing Tournament</h2>
    <h6 class="card-subtitle mb-2 text-muted">Edit carefully all fields...</h6>
    <%= render 'form', tournament: @tournament %>
  </div>
</div>

app/views/admins/tournaments/index.html.erb
<p class="text-end"><%= link_to 'New Tournament', new_tournament_path, class: 'btn btn-primary m-3' %></p>
<div class="container">
  <% @tournaments.map {|x| [x.active ? 0 : 1, x ]}.sort.map { |x| x.second }
.each do |tournament| %>
    <div class="post-card">
      <p class="spy-eye text-end">
        <%= link_to tournament, class: 'btn btn-primary m-3' do %>
          <span class="material-icons">add_box</span>
        <% end %>
        <%= link_to edit_tournament_path(tournament), class: 'btn btn-primary m-3' do %>
          <span class="material-icons">edit</span>
        <% end %>
        <%= link_to tournament, method: :delete, data: {confirm: "Do you really want to delete #{tournament.title} tournament?"}, class: 'btn btn-danger m-3' do %>
          <span class="material-icons">delete</span>
        <% end %>
      </p>
      <%= link_to tournament_path(tournament), class: 'text-decoration-none' do %>
        <div class="card mb-3">
          <div class="card-body">
            <div class="row">
              <div class="col-md-4 tournament-box">
                <p class="card-text lead"><%= tournament.title %></p>
                <% if tournament.active %>
                  <p class="badge badge-pill badge-success bg-success">Active</p>
                <% else %>
                  <p class="badge badge-pill badge-success bg-danger">Unactive</p>
                <% end %>
                <br>
                <span class="badge badge-pill bg-secondary badge-secondary"><%= tournament.start_date.strftime("%d/%m/%Y") %> - <%= tournament.end_date.strftime("%d/%m/%Y") %></span>
              </div>
              <div class="col-md-8">
                <p class="card-text text-center text-dark">Contenders</p>
                <div class="d-flex flex-wrap justify-content-center">
                  <% tournament.puzzle_contenders.map { |x| [x.votes.count, x] }.sort.reverse.map {|x| x.second}.each do |contender| %>
                    <% if contender.puzzle.image.present? %>
                      <div class="tournament_puzzle_image" style="background-image: url(<%= url_for(contender.puzzle.image) %>);"><p class="vote-count lead"><span class="badge badge-pill text-secondary bg-light"><%= contender.votes.count %><span class="material-icons vote-icon">favorite</span></span></p></div>
                    <% else %>
                      <div class="card lead bg-dark text-light tournament_puzzle_image text-center">
                        <%= contender.puzzle.title %>
                        <div class="m-auto">
                          <p class="badge badge-pill text-secondary bg-light"><%= contender.votes.count %><span class="material-icons vote-icon">favorite</span>
                          </p>
                      </div>
                      </div>
                    <% end %>
                  <% end %>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/admins/tournaments/new.html.erb
<div class="card m-0 p-0 no-border-card">
  <%= link_to 'Back', tournaments_path, class: 'btn btn-dark m-3 col-2' %>
  <div class="card-body text-center">
    <h2 class="card-title">New Tournament</h2>
    <h6 class="card-subtitle mb-2 text-muted">Fill carefully all fields...</h6>
	<%= render 'form', tournament: @tournament %>
  </div>
</div>

app/views/admins/tournaments/show.html.erb
<div class="jumbotron bg-light p-2 admin-jumbotron">
  <h1 class="display-4 text-center m-0  "><%= @tournament.title %></h1>
  <h6 class="text-center m-0"><span class="badge badge-pill bg-secondary badge-secondary"><%= @tournament.start_date.strftime("%d/%m/%Y") %> - <%= @tournament.end_date.strftime("%d/%m/%Y") %></span></h6>
  <p class="lead">
    Total contenders: <%= @tournament.puzzle_contenders.count %>
    <br>
    Total Votes: <%= @total_votes %>
    <br>
    <div class="text-center container lead">
      <% if !@tournament.current_winner.nil? && @tournament.current_winner.any? %>
        Leaderboard <span class="badge badge-pill badge-success bg-success mb-2"><%= @tournament.current_winner.first.second.count %><span class="winner-badge material-icons">military_tech</span></span>
        <ul class="list-group">
          <li class="list-group-item d-flex justify-content-around align-items-center"><h5 class="m-0">CONTENDERS</h4><h4 class="m-0">VOTES</h5></li>
          <% @tournament.current_winner.each do |element| %>
          <li class="list-group-item d-flex justify-content-around align-items-center">
            <span>
              <% element.second.each do |contender| %>
                <% if contender.second.persisted? %>
                  <div class="puzzle-contender-info">
                    <%= link_to contender.second, method: :delete, class: "text-decoration-none" do %>
                      <span class="material-icons trash-icon text-danger text">delete</span>
                    <% end %>
                    <%= link_to contender.second.puzzle, class: "text-decoration-none users-tooltip" do %>
                      <%= contender.second.puzzle.title %>
                      <% if contender.second.votes.any? %>
                        <span class="tooltiptext p-2 bg-dark text-light"><%= contender.second.votes.map { |vote| vote.username }.join(", ") %></span>
                      <% else %>
                        <span class="tooltiptext p-2 bg-dark text-light">No votes :(</span>
                      <% end %>
                    <% end %>
                    <!--<= render "vote_contender_form", vote: @vote, contender: contender.second >-->
                  </div>
                  <% unless contender.eql?(element.second.last) %>
                    <hr>
                  <% end %>
                <% end %>
              <% end %>
            </span>
            <span class="badge badge-primary badge-pill bg-primary"><%= element.first %></span>
          </li>
          <% end %>
        </ul>
      <% else %>
        No contenders or votes so far
      <% end %>
    </div>
  </p>
  <hr class="my-4">
  <div class="card ms-5 me-5 text-center">
    <div class="card-body">
      <h5 class="card-title">New Contender</h5>
      <%= render "contenders_form", tournament: @tournament, contender: @contender %>
    </div>
  </div>
  <hr class="my-4">
  <p class="lead text-center p-2 m-2">
    <%= link_to 'Edit', edit_tournament_path(@tournament), class: "btn btn-primary btn-lg" %>  
    <%= link_to 'Destroy', @tournament, method: :delete, class: "btn btn-danger btn-lg" %>
  </p>
</div>