config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  scope module: 'admins' do
    get 'admin_home'
    get 'notifications'
    resources :puzzles
    resources :memories
    resources :tournaments
    resources :contributors, only: [:new, :create, :destroy, :edit, :update, :index]
    resources :text_memories
    resources :image_memories
    resources :puzzle_contenders, only: [:new, :create, :destroy] do
      resources :votes
    end
  end
  scope module: 'visitors' do
    root to: "home#index"
    post 'votes', to: 'home#votes'
    get '/home/current_puzzle' => 'home#current_puzzle', as: 'current_puzzle'
    get '/home/puzzle/:id' => 'puzzles#show', as: 'visitors_puzzle' 
    get '/home/puzzles/index' => 'puzzles#index', as: 'visitors_puzzles'
    get '/home/tournaments'  => 'home#tournaments', as: 'visitor_torunaments'
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contributor.rb
class Contributor < ApplicationRecord
  belongs_to :puzzle
end

app/models/image_memory.rb
class ImageMemory < ApplicationRecord
  belongs_to :memory
  has_one_attached :image
end

app/models/memory.rb
class Memory < ApplicationRecord
  has_many :image_memories, dependent: :destroy
  has_many :text_memories, dependent: :destroy
  belongs_to :puzzle
  accepts_nested_attributes_for :image_memories, :text_memories
  validates :user_names42, presence: true

  def active_memories
    image_memories.where(active: true).count + text_memories.where(active: true).count > 0 ? true : nil
  end
end

app/models/puzzle.rb
class Puzzle < ApplicationRecord
	has_many :memories, dependent: :destroy
	has_many :contributors, dependent: :destroy
	has_many :puzzle_contenders, dependent: :destroy
	has_one_attached :image
end

app/models/puzzle_contender.rb
class PuzzleContender < ApplicationRecord
  belongs_to :tournament
  belongs_to :puzzle
  has_many :votes, dependent: :destroy
  validate :duplicated_puzzle

  private

    def duplicated_puzzle
      if self.tournament.puzzles.where(id: puzzle_id).any?
        errors.add(:puzzle_id, "The puzzle already belongs to this Tournament")
      end
    end
end

app/models/text_memory.rb
class TextMemory < ApplicationRecord
  belongs_to :memory
  validates :title, :description, presence: true
end

app/models/tournament.rb
class Tournament < ApplicationRecord
	has_many :puzzle_contenders, dependent: :destroy
	has_many :puzzles, through: :puzzle_contenders
	has_many :votes, through: :puzzle_contenders
	
	def available_puzzle_contenders
		Puzzle.where.not(id: self.puzzles)
	end
	
	def current_winner
      self.puzzle_contenders.map { |contender| [contender.votes.count, contender]}.group_by { |element| element [0] }.max(3)
    end

    def active
    	start_date < Time.now && end_date > Time.now
    end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :puzzle_contender
  validates_presence_of :username
  validate :valid_user_42api, :duplicated_vote, :active_tournament

  private

    def valid_user_42api
      user = username.downcase.strip
      client = OAuth2::Client.new(Rails.application.credentials.api42_uid, Rails.application.credentials.api42_secret, site: "https://api.intra.42.fr")
      token = client.client_credentials.get_token
      puts ">>>" * 10 + "---" * 20 + "<<<" * 10
      begin
        response = token.get("/v2/users/" + user)
        puts "Response: (should be 200): " + response.status.to_s
        puts "New Vote registered"
        puts "Login: " + response.parsed["login"]
        puts "Campus: " + response.parsed["campus"].first["country"]
        puts "Puzzle: " + self.puzzle_contender.puzzle.title +  " | Last Votes Count: " + self.puzzle_contender.votes.count.to_s
      rescue
        puts "something went wrong when check if #{user} exists..."
        errors.add(:username, "Not a valid username __REASON_TODO__")
      end
      puts ">>>" * 10 + "-*-" * 20 + "<<<" * 10
    end

    def duplicated_vote
      if self.puzzle_contender.tournament.votes.where(username: username).any?
          errors.add(:username, "That username has been used once already :( ")
      end
    end

    def active_tournament
      if not self.puzzle_contender.tournament.active
        errors.add(:puzzle_contender, "The Tournament is not active atm :( ")
      end
    end
end

app/controllers/admins/contributors_controller.rb
module Admins
  class ContributorsController < AdminsController
    before_action :set_contributor, only: %i[ edit update destroy ]

    # GET /contributors or /contributors.json
    def index
      @contributors = Contributor.all
    end

    # GET /contributors/new
    def new
      @contributor = Contributor.new
    end

    # GET /contributors/1/edit
    def edit
    end

    # POST /contributors or /contributors.json
    def create
      @contributor = Contributor.new(contributor_params)

      respond_to do |format|
        if @contributor.save
          format.html { redirect_to contributors_url, notice: "Contributor was successfully created." }
          format.json { render :index, status: :created, location: contributors_url }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @contributor.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /contributors/1 or /contributors/1.json
    def update
      respond_to do |format|
        if @contributor.update(contributor_params)
          format.html { redirect_to contributors_url, notice: "Contributor was successfully updated." }
          format.json { render :index, status: :ok, location: contributors_url }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @contributor.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /contributors/1 or /contributors/1.json
    def destroy
      @contributor.destroy
      respond_to do |format|
        format.html { redirect_to contributors_url, notice: "Contributor was successfully destroyed." }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_contributor
        @contributor = Contributor.find(params[:id])
      end

      # Only allow a list of trusted parameters through.
      def contributor_params
        params.require(:contributor).permit(:puzzle_id, :is_finished, :finish_date)
      end
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :authenticate_admin!, :notifications_count
	layout 'admin'

	def admin_home
		@puzzles = Puzzle.all
		@total_notifications = ImageMemory.where(active: false).count + TextMemory.where(active: false).count
		@tournaments = Tournament.all
		@contributors = Contributor.all
	end

	def notifications
		@image_memories = ImageMemory.where(active: false)
		@text_memories = TextMemory.where(active: false)
	end

	private

		def notifications_count
			@notifications_count = ImageMemory.where(active: false).count + TextMemory.where(active: false).count
		end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contributors_helper.rb
module ContributorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/memories_helper.rb
module MemoriesHelper
end

app/helpers/puzzle_helper.rb
module PuzzleHelper
end

app/helpers/puzzles_helper.rb
module PuzzlesHelper
end

app/helpers/text_memories_helper.rb
module TextMemoriesHelper
end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/admins/contributors/_form.html.erb
<%= form_with(model: contributor) do |form| %>
  <% if contributor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contributor.errors.count, "error") %> prohibited this contributor from being saved:</h2>

      <ul>
        <% contributor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
    <div class="field">
      <%= form.label :puzzle_id, class: "form-control"%>
      <%= form.collection_select :puzzle_id, Puzzle.all, :id, :title, {}, class: "form-control" %>
    </div>

    <div class="form-field">
      <%= form.label :is_finished %>
      <%= form.check_box :is_finished, class: "m-4" %>
    </div>

    <div class="input-group form-field">
      <div class="field-tag">
        <div class="input-group-prepend" >
          <span class="input-group-text tag-style">
            <%= form.label :finish_date %>
          </span>
        </div>
      </div>
      <%= form.date_field :finish_date, class: 'form-control' %>
    </div>

    <div class="actions">
      <%= form.submit 'Submit', :class => 'form-control btn btn-primary'  %>
    </div>
  </div>
<% end %>

app/views/admins/contributors/edit.html.erb
<div class="card m-0 p-0 no-border-card">
    <%= link_to 'Back', contributors_path, class: 'btn btn-dark m-3 col-2' %>
	<div class="card-body text-center">
		<h2 class="card-title">Editing Contributor</h2>
		<h6 class="card-subtitle mb-2 text-muted">Edit carefully all fields (Images will be overwritten)...</h6>
		<%= render 'form', contributor: @contributor %>
	</div>
</div>

app/views/admins/contributors/index.html.erb
<p class="text-end"><%= link_to 'New Contributor', new_contributor_path, class: 'btn btn-primary m-3' %></p>

<div class="container">
  <% @contributors.each do |contributor| %>
    <div class="post-card">
      <p class="spy-eye text-end">
        <%= link_to puzzle_path(contributor.puzzle), class: 'btn btn-primary m-3' do %>
          <span class="material-icons">extension</span>
        <% end %>
        <%= link_to contributor, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger m-3" do %>
          <span class="material-icons">delete</span>
        <% end %>
      </p>
      
      <%= link_to edit_contributor_path(contributor), class: 'text-decoration-none' do %>
        <div class="card mb-3">
          <div class="card-body">
            <div class="row">
              <div class="col-md-2">
                <% if contributor.puzzle.image.present? %>
                  <div class="header_image" style="background-image: url(<%= url_for(contributor.puzzle.image) %>);"></div>
                <% end %>
              </div>
              <div class="col-md-6">
                <h5 class="card-title"><%= contributor.puzzle.title %></h5>
                <p class="card-text"><%= contributor.puzzle.description.truncate(150) %></p>
              </div>
              <div class="col-md-4 contributor-borders">
                <p class="badge badge-pill badge-primary bg-secondary">
                  <%= contributor.created_at.strftime("%d/%m/%Y") %>
                </p>
                <br>
                <% if contributor.is_finished? %>
                  <p class="badge badge-pill badge-success bg-success">
                    Finished
                  </p>  
                <% else %>
                  <p class="badge badge-pill badge-info bg-info">
                    In progress
                  </p>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/admins/contributors/new.html.erb
<div class="card m-0 p-0 no-border-card">
  <%= link_to 'Back', contributors_path, class: 'btn btn-dark m-3 col-2' %>
  <div class="card-body text-center">
    <h2 class="card-title">New Contributor</h2>
    <h6 class="card-subtitle mb-2 text-muted">Fill carefully all fields...</h6>
	<%= render 'form', contributor: @contributor %>
  </div>
</div>